name: CI - PG App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🟢 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 🔧 Install dependencies (backend)
        working-directory: ./backend
        run: npm install

      - name: 🔧 Install dependencies (frontend)
        working-directory: ./frontend
        run: npm install

      - name: 🛠️ Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: ✅ Lint commit messages (optional)
        run: npx --no -- commitlint --from=HEAD~1 || echo "Skipping commitlint if no commits"
